@echo off
echo Cleaning up .next directory...
cd /d C:\Users\USER\Desktop\banking-app
rmdir /s /q .next
echo Making sure .babelrc is removed...
if exist .babelrc del .babelrc
echo Starting development server...
npm run dev
